worker:
  build: docker
  volumes:
    - "/pwd/software:/gan-lib"
    - "/usr/local/cuda:/usr/local/cuda"
    - "/usr/lib/nvidia-367:/usr/local/nvidia"
    - "/usr/lib/x86_64-linux-gnu/libcuda.so:/usr/lib/x86_64-linux-gnu/libcuda.so"
    - "/usr/lib/x86_64-linux-gnu/libcuda.so.1:/usr/lib/x86_64-linux-gnu/libcuda.so.1"
    - "/usr/lib/x86_64-linux-gnu/libcuda.so.367.57:/usr/lib/x86_64-linux-gnu/libcuda.so.367.57"
  devices:
    - "/dev/nvidia0:/dev/nvidia0"
    - "/dev/nvidiactl:/dev/nvidiactl"
    - "/dev/nvidia-modeset:/dev/nvidia-modeset"
    - "/dev/nvidia-uvm:/dev/nvidia-uvm"
