FROM image

ADD requirements.txt /root
RUN pip install -r /root/requirements.txt && \
    rm -rf /root/.cache/pip/*

ENV PATH="/usr/local/cuda/bin:/usr/local/nvidia/bin:/usr/lib/x86_64-linux-gnu:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:/usr/local/nvidia:/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"

WORKDIR /gan-lib/